## DeepSeek
# @model = deepseek-chat
# @provider = deepseek

## Google
@model = gemini-2.5-flash-preview-04-17
# @model = gemini-2.0-flash-thinking-exp-01-21
@provider = google

### Query example #1
POST http://localhost:8082/ai/query
Content-Type: application/json

{
	"model": "{{model}}",
	"provider": "{{provider}}",
	"prompt": "What is Paris exact population as of January 2025?",
	"scrapeUrls": [
		"https://en.wikipedia.org/wiki/Paris"
	]
}

### Query example #2
POST http://localhost:8082/ai/query
Content-Type: application/json

{
	"model": "{{model}}",
	"provider": "{{provider}}",
	"prompt": "At what time is the discount price?",
	"scrapeUrls": [
		"https://api-docs.deepseek.com/quick_start/pricing/"
	]
}

### Query example #3
POST http://localhost:8082/ai/query
Content-Type: application/json

{
	"model": "{{model}}",
	"provider": "{{provider}}",
	"prompt": "What is the title of point 1.3 in the document?",
	"fileUrls": [
		"https://www.unirioja.es/cu/jearansa/1011/ficheros/Tema_1.pdf"
	]
}

### Image
POST http://localhost:8082/ai/query
Content-Type: application/json

{
	"model": "{{model}}",
	"provider": "{{provider}}",
	"prompt": "What model and color is this car? where is it?",
	"images": ["https://images.ecestaticos.com/wb5YEYVsYJBCsOxoXg1uUG8a8lo=/0x157:2273x1434/1338x752/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2F2f2%2Fe05%2F3d3%2F2f2e053d3200c826f0d514cfe6981282.jpg"]
}

### Video
POST http://localhost:8082/ai/query
Content-Type: application/json

{
	"model": "{{model}}",
	"provider": "{{provider}}",
	"prompt": "Generate a summary for this video",
	"videos": [
		"asdf.mp4"
	]
}
